### ISSUE TITLE
Required files to compile

### ISSUE THREAD

**Issue by smlinux** [SmartisanTech/U1Kernel#1]
Here are no required directories and files to compile:
`
drivers/infiniband/core
drivers/memstick/core
drivers/mmc/core
drivers/usb/core
net/core
sound/aoa/core
sound/core
`
and _wlan driver_
`
drivers/staging/prima
`
 Will this be fixed?

**Comment by baohaojun** [comment]
The core files have been added, my bad.

There is no plan to release the wlan driver, sorry.
